//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_EcareWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        [Required]
        [EmailAddress]
        public string email { get; set; }

        [Required]
        public string sex { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public string birthday { get; set; }
        public string bloodType { get; set; }
        public string allergies { get; set; }
        public string situation { get; set; }
        public string userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
