//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace FIT5032_EcareWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int doctorId { get; set; }

        [Required]
        [Display(Name ="Your Name")]
        public string doctorName { get; set; }

        [Required, Display(Name ="Set your password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Required, Display(Name ="Your Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        public string description { get; set; }
        public string score { get; set; }
        public int Hospital_hospitalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
