//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_EcareWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5032_EcareModelContainer : DbContext
    {
        public FIT5032_EcareModelContainer()
            : base("name=FIT5032_EcareModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Service> ServiceSet { get; set; }
        public virtual DbSet<Doctor> DoctorSet { get; set; }
        public virtual DbSet<Hospital> HospitalSet { get; set; }
    }
}
