//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_EcareWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serviceId { get; set; }
        public string price { get; set; }
        public string content { get; set; }
        public string score { get; set; }
        public string date { get; set; }
        public int User_userId { get; set; }
        public int Doctor_doctorId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
